import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AppStateProvider } from '@/utils/AppStateProvider';
import Wrapper from '@/components/Wrapper';
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="en">
      <AppStateProvider>
        <body className={`
          ${inter.className}
          relative w-screen h-screen min-w-80
        `}>
          <Wrapper>
            { children }
          </Wrapper>

          <NavBar />
        </body>
      </AppStateProvider>
    </html>
  );
}
