import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { getAuthenticatedAppForUser } from "@/app/lib/firebase/firebase";
import TestHeader from "./components/TestHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { currentUser } = await getAuthenticatedAppForUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <TestHeader initialUser={currentUser?.toJSON()}/>

        <main>{children}</main>
      </body>
    </html>
  );
}
